In [1]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [1]:
# Creating a numpy array using a python List
import numpy 

li = [5.6,7.8,9.0]
np_array1 = numpy.array(li)
print(np_array1)
print(type(np_array1))

[5.6 7.8 9. ]
<class 'numpy.ndarray'>


In [2]:
# Creating a numpy array using a python tuple
import numpy 

li = (5.6,7.8,9.0)
np_array2 = numpy.array(li)
print(np_array2)
print(type(np_array2))

[5.6 7.8 9. ]
<class 'numpy.ndarray'>


In [3]:
# Creating a numpy array using a python Range 
import numpy 

np_array3 = numpy.array([range(1,21,2)])
print(np_array3)
print(type(np_array3))

[[ 1  3  5  7  9 11 13 15 17 19]]
<class 'numpy.ndarray'>


### Creating 1-D array

In [13]:
# Creating a numpy array using a python Range 
import numpy 

li = list(range(1,21,2))
np_array3 = numpy.array(li)
print(np_array3)
print(type(np_array3))
print(np_array3.ndim)
print(np_array3.shape)

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
1
(10,)


### Creating 2-D array

In [14]:
np_array4 = numpy.array([[34,56],[56,78],[89,56]])
print(np_array4)
print(type(np_array4))
print(np_array4.ndim)
print(np_array4.shape)

[[34 56]
 [56 78]
 [89 56]]
<class 'numpy.ndarray'>
2
(3, 2)


### Creating 3-D array

In [38]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]])
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45 67]
  [67 78]
  [67 89]]

 [[12 45]
  [45 34]
  [67 88]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
Total size used by array:  48


## Creating 4-D array

In [16]:
np_array6 = numpy.array([[[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]]])
print(np_array6)
print(type(np_array6))
print(np_array6.ndim)
print(np_array6.shape)

[[[[45 67]
   [67 78]
   [67 89]]

  [[12 45]
   [45 34]
   [67 88]]]]
<class 'numpy.ndarray'>
4
(1, 2, 3, 2)


## Creating 10-D array

In [ ]:
np_array7 = numpy.array([[[[[[[[[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]]]]]]]]])
print(np_array7)
print(type(np_array7))
print(np_array7.ndim)

In [20]:
# Creating a 3-D array using reshape method
np_array = numpy.arange(1,51)
np_array3d = np_array.reshape(2,5,5)
print(np_array3d)
print(np_array3d.ndim)
print(np_array3d.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
3
(2, 5, 5)


In [21]:
# Creating a 3-D array using reshape method
np_array = numpy.arange(1,61)
np_array3d = np_array.reshape(2,5,-1)
print(np_array3d)
print(np_array3d.ndim)
print(np_array3d.shape)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]
  [25 26 27 28 29 30]]

 [[31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(2, 5, 6)


In [22]:
# Creating a 10-D array using reshape method

np_array = numpy.arange(1,49)
np_array10d = np_array.reshape(1,1,1,1,1,1,2,2,3,4)
print(np_array10d)
print(np_array10d.ndim)
print(np_array10d.shape)

[[[[[[[[[[ 1  2  3  4]
         [ 5  6  7  8]
         [ 9 10 11 12]]

        [[13 14 15 16]
         [17 18 19 20]
         [21 22 23 24]]]


       [[[25 26 27 28]
         [29 30 31 32]
         [33 34 35 36]]

        [[37 38 39 40]
         [41 42 43 44]
         [45 46 47 48]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 2, 2, 3, 4)


In [24]:
# Creating a 4-D array using reshape method

li = list(range(1,82))
ar = numpy.array(li)
arr4b = ar.reshape(3,3,3,-1) # last dimension(column) will be automatically calculated
arr4b

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])

### Create an array with specified data type

In [37]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='int8')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45 67]
  [67 78]
  [67 89]]

 [[12 45]
  [45 34]
  [67 88]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
int8
Total size used by array:  12


In [39]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='float16')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45. 67.]
  [67. 78.]
  [67. 89.]]

 [[12. 45.]
  [45. 34.]
  [67. 88.]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
float16
Total size used by array:  24


In [41]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='complex64')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45.+0.j 67.+0.j]
  [67.+0.j 78.+0.j]
  [67.+0.j 89.+0.j]]

 [[12.+0.j 45.+0.j]
  [45.+0.j 34.+0.j]
  [67.+0.j 88.+0.j]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
complex64
Total size used by array:  96


In [ ]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='int8')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

In [47]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='U1')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[['4' '6']
  ['6' '7']
  ['6' '8']]

 [['1' '4']
  ['4' '3']
  ['6' '8']]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
<U1
Total size used by array:  48


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [3]:
# numpy.arange(start, stop, step)

import numpy

np_array1 = numpy.arange(21)
print(np_array1)
print(type(np_array1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [4]:
np_array2 = numpy.linspace(1,20,4)
print(np_array2)

[ 1.          7.33333333 13.66666667 20.        ]


### Create an array of random values of given shape
```numpy.random.rand()``` method returns values in the range [0,1)

In [16]:
import random

random.seed(1234)
for i in range(10):
    print(random.randint(15,51))

43
22
15
20
17
20
21
37
30
16


In [6]:
np_array3 = numpy.random.rand(4,3)
print(np_array3)

[[0.26415367 0.70395803 0.99821484]
 [0.18899255 0.24107548 0.94185737]
 [0.21832483 0.29145085 0.58265098]
 [0.12393459 0.77619144 0.40664701]]


In [20]:
np_array4 = numpy.random.randint(1,100, size = (3,3))
print(np_array4)

[[89 76 59]
 [41  9 69]
 [97 97 62]]


### Create an array of zeros of given shape 
- ```numpy.zeros()```: create array of all zeros in given shape
- ```numpy.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [22]:
np_array5 = numpy.zeros((2,3))
print(np_array5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# Array of integer zero

np_array6 = numpy.zeros((2,3), dtype=int)
print(np_array6)

[[0 0 0]
 [0 0 0]]


In [26]:
# Array of complex zero

np_array7 = numpy.zeros((2,3), dtype = complex)
print(np_array7)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


### Create an array of ones of given shape 
- ```numpy.ones()```: create array of all ones in given shape
- ```numpy.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [32]:
np_array8 = numpy.ones((3,4))
print(np_array8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
np_array8 = numpy.ones((3,4), dtype=str)
print(np_array8)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [37]:
np_array9 = numpy.empty((3,3,3))
print(np_array9)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.29061074e-306 1.69119873e-306 1.78019082e-306]
  [3.11518149e-307 4.22779312e-307 2.33644299e-307]]

 [[7.56587584e-307 1.37961302e-306 1.05699242e-307]
  [8.01097889e-307 1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 2.04719290e-306 1.00132653e-307]]

 [[8.01097889e-307 1.29062229e-306 1.69111725e-306]
  [1.69118923e-306 1.11260144e-306 6.89812281e-307]
  [2.22522596e-306 1.11253693e-306 2.10081501e-312]]]


In [41]:
np_array10 = numpy.empty_like(([1,2,3], [4,5,6]), shape=(2,2,2))
print(np_array10)
# print(np_array10.dtype)

[[[         0 1072693248]
  [1431655765 1075664213]]

 [[1431655765 1076581717]
  [         0 1077149696]]]
int32


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [44]:
np_array11 = numpy.full((2,3,4),4)
print(np_array11)

[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]]


In [53]:
np_array11 = numpy.full((2,3,4),[[1,2,3,5],[6,7,4,2],[6,7,5,4]])
print(np_array11)

[[[1 2 3 5]
  [6 7 4 2]
  [6 7 5 4]]

 [[1 2 3 5]
  [6 7 4 2]
  [6 7 5 4]]]


### Create an array in a repetitive manner
- ```numpy.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```numpy.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [54]:
# No axis specified, then flatten the input array first and repeat

np_array12 = numpy.repeat([3,4,5],3)
print(np_array12)

[3 3 3 4 4 4 5 5 5]


In [59]:
np_array12 = numpy.repeat([3,4,5],3, axis=0)
print(np_array12)
print(np_array12.shape)

[3 3 3 4 4 4 5 5 5]
(9,)


In [58]:
np_array12 = numpy.repeat([3,4,5],3, axis=1)
print(np_array12)

AxisError: axis 1 is out of bounds for array of dimension 1

In [60]:
np_array14 = numpy.repeat([[3,4,5],[1,2,3]],3, axis=0)
print(np_array14)

[[3 4 5]
 [3 4 5]
 [3 4 5]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
np_array14 = numpy.repeat([[3,4,5],[1,2,3]],3, axis=0)
print(np_array14)

In [62]:
np_array15 = numpy.repeat([[3,4,5],[1,2,3]],3, axis=1)
print(np_array15)

[[3 3 3 4 4 4 5 5 5]
 [1 1 1 2 2 2 3 3 3]]


In [56]:
np_array13 = numpy.tile([[3,4,5],[1,2,3]],3)
print(np_array13)

[[3 4 5 3 4 5 3 4 5]
 [1 2 3 1 2 3 1 2 3]]


In [65]:
np_array13 = numpy.tile([[3,4,5],[1,2,3]],3, axis=0)
print(np_array13)

TypeError: _tile_dispatcher() got an unexpected keyword argument 'axis'

### Create an identity matrix of given size
- ```numpy.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```numpy.identity()```: same as ```np.eye()``` but does not carry parameters

In [79]:
np_array16 = numpy.eye(3,3)
print(np_array16)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [80]:
np_array17 = numpy.identity(3)
print(np_array17)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [87]:
# An example of diagonal offset
identity_matrix = numpy.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [93]:
identity_matrix = numpy.identity(5, dtype=int)
print(identity_matrix)

TypeError: identity() got an unexpected keyword argument 'k'

### Create an array with given values on the diagonal

In [96]:
arr = numpy.random.randint(1,51,(5,5))
print(arr)

# Extract values on the diagonal
print('Values on the diagonal: ' + str(numpy.diag(arr)))

[[33 24 10 40 31]
 [20 10 13 36 21]
 [31 45 30 30 19]
 [34 40 36 19 12]
 [14 32  2 25 31]]
Values on the diagonal: [33 10 30 19 31]


In [97]:
# Not necessarily to be a square matrix
arr = numpy.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(numpy.diag(arr)))

[[5.31874531e-01 6.76804030e-01 1.37045666e-01]
 [3.19146242e-01 7.00107883e-01 9.92152277e-01]
 [2.59797646e-01 4.70029548e-01 2.09439951e-02]
 [8.41317197e-02 5.28932542e-01 8.87209194e-01]
 [7.15616170e-01 3.34432746e-01 4.56285875e-01]
 [6.67885959e-04 9.24585823e-01 1.97979247e-01]
 [7.31197457e-01 3.59554252e-01 7.00653252e-01]
 [5.63648524e-01 9.76472056e-01 6.65889551e-02]
 [4.10882617e-01 4.08662613e-01 5.36724257e-01]
 [3.37930989e-01 3.60985701e-01 4.63196544e-01]]
Values on the diagonal: [0.53187453 0.70010788 0.020944  ]


In [90]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
