In [1]:
import numpy as np

In [28]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,10,11,12], [13,14,15,16]])
print(arr1)
print()
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [13 14 15 16]]


### ```np.concatenate((a, b), axis=0)```

In [12]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [18]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.   8. ]
 [ 1.1  1.2  1.3  1.4]
 [ 9.  10.  11.  12. ]
 [13.  14.  15.  16. ]]


In [19]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.   8. ]
 [ 1.1  1.2  1.3  1.4]
 [ 9.  10.  11.  12. ]
 [13.  14.  15.  16. ]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [29]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [30]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


### split an array 

In [24]:
arr = np.random.rand(4,4)
arr

array([[0.0432893 , 0.11940108, 0.91087629, 0.47418018],
       [0.60234587, 0.79521682, 0.58406373, 0.47085567],
       [0.09175111, 0.93588922, 0.9907967 , 0.53389941],
       [0.87995587, 0.06607412, 0.60158288, 0.44377659]])

In [26]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.0432893 , 0.11940108, 0.91087629, 0.47418018],
       [0.60234587, 0.79521682, 0.58406373, 0.47085567]]), array([[0.09175111, 0.93588922, 0.9907967 , 0.53389941],
       [0.87995587, 0.06607412, 0.60158288, 0.44377659]])]


In [27]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.0432893 , 0.11940108],
       [0.60234587, 0.79521682],
       [0.09175111, 0.93588922],
       [0.87995587, 0.06607412]]), array([[0.91087629, 0.47418018],
       [0.58406373, 0.47085567],
       [0.9907967 , 0.53389941],
       [0.60158288, 0.44377659]])]
