In [2]:
import numpy as np

In [4]:
arr = np.random.rand(5,5)
arr

array([[0.11265171, 0.36981752, 0.50567324, 0.17688009, 0.95565127],
       [0.26389068, 0.48930256, 0.3569989 , 0.1665544 , 0.37571573],
       [0.3956903 , 0.9401187 , 0.10203714, 0.89936963, 0.55532569],
       [0.37721127, 0.56978506, 0.73525308, 0.7503126 , 0.95772701],
       [0.13475401, 0.11738278, 0.42761014, 0.99731881, 0.91971682]])

### sort an array along a specified axis

In [5]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.11265171 0.11738278 0.10203714 0.1665544  0.37571573]
 [0.13475401 0.36981752 0.3569989  0.17688009 0.55532569]
 [0.26389068 0.48930256 0.42761014 0.7503126  0.91971682]
 [0.37721127 0.56978506 0.50567324 0.89936963 0.95565127]
 [0.3956903  0.9401187  0.73525308 0.99731881 0.95772701]]


In [6]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.11265171 0.11738278 0.10203714 0.1665544  0.37571573]
 [0.13475401 0.36981752 0.3569989  0.17688009 0.55532569]
 [0.26389068 0.48930256 0.42761014 0.7503126  0.91971682]
 [0.37721127 0.56978506 0.50567324 0.89936963 0.95565127]
 [0.3956903  0.9401187  0.73525308 0.99731881 0.95772701]]


In [7]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.10203714 0.11265171 0.11738278 0.1665544  0.37571573]
 [0.13475401 0.17688009 0.3569989  0.36981752 0.55532569]
 [0.26389068 0.42761014 0.48930256 0.7503126  0.91971682]
 [0.37721127 0.50567324 0.56978506 0.89936963 0.95565127]
 [0.3956903  0.73525308 0.9401187  0.95772701 0.99731881]]


In [8]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.10203714 0.11265171 0.11738278 0.1665544  0.37571573]
 [0.13475401 0.17688009 0.3569989  0.36981752 0.55532569]
 [0.26389068 0.42761014 0.48930256 0.7503126  0.91971682]
 [0.37721127 0.50567324 0.56978506 0.89936963 0.95565127]
 [0.3956903  0.73525308 0.9401187  0.95772701 0.99731881]]


### compute the indices that would sort an array along a specified axis

In [7]:
arr = np.random.rand(5,5)

In [8]:
# along the row
print(np.argsort(arr, axis=0))

[[1 1 2 2 0]
 [2 2 1 3 2]
 [0 4 0 1 4]
 [4 3 3 0 3]
 [3 0 4 4 1]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[4 3 2 0 1]
 [0 3 1 2 4]
 [3 2 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[13 12  5 18  4  8  6  7 14  3 10 24  2 11  0 19 20 21  9 15 16 17 22  1
 23]
