In [1]:
import numpy as np

In [7]:
import numpy as np
arr = np.random.rand(3,4)
print(arr)

[[0.85220164 0.55063512 0.21396392 0.39158096]
 [0.14235283 0.11571815 0.4152929  0.93522441]
 [0.74450508 0.66848915 0.62889911 0.09848999]]


### Transpose an array

In [3]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.98440661 0.95953312 0.30401979]
 [0.15315942 0.01093673 0.59247041]
 [0.3330772  0.90659178 0.81129995]
 [0.45128527 0.99198992 0.82223538]]
[[0.98440661 0.95953312 0.30401979]
 [0.15315942 0.01093673 0.59247041]
 [0.3330772  0.90659178 0.81129995]
 [0.45128527 0.99198992 0.82223538]]
[[0.98440661 0.95953312 0.30401979]
 [0.15315942 0.01093673 0.59247041]
 [0.3330772  0.90659178 0.81129995]
 [0.45128527 0.99198992 0.82223538]]


### Transpose of a high dimensional array with specified order of axes

In [8]:

import numpy as np
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

print("***************************")




arr1.transpose((1,0,2))
print(arr1)

ValueError: cannot reshape array of size 16 into shape (1,2,4)

### Swap axes

In [5]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### Change the shape of an array

In [6]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
        0.01093673],
       [0.90659178, 0.99198992, 0.30401979, 0.59247041, 0.81129995,
        0.82223538]])

In [7]:
# change the shape of an array in place
arr.resize((2,6))

### Flatten an array

In [8]:
# return a copy
arr.flatten()    

array([0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
       0.01093673, 0.90659178, 0.99198992, 0.30401979, 0.59247041,
       0.81129995, 0.82223538])

In [9]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
       0.01093673, 0.90659178, 0.99198992, 0.30401979, 0.59247041,
       0.81129995, 0.82223538])

### Append elements to an array

In [10]:
arr = np.array([1,2,3])

In [11]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [12]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### Insert elements into an array

In [13]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [14]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### Delete elements from an array

In [15]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [16]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### Copy an array

In [17]:
arr = np.array([1,2,3])

In [18]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)